CREATE DATABASE BlackBoard
GO

USE BlackBoard
GO

CREATE TABLE Teacher(
	Birthday Date,
	Name NVARCHAR(50),
	TeacherID NVARCHAR(10) NOT NULL PRIMARY KEY
)
GO

CREATE TABLE Course(
	CourseID NVARCHAR(10) NOT NULL PRIMARY KEY,
	Name NVARCHAR(50)
)
GO


CREATE TABLE TeachesCourse(
	CourseID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Course(CourseID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	TeacherID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Teacher(TeacherID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	Role NVARCHAR(50),
	PRIMARY KEY(CourseID, TeacherID)

)
GO




CREATE TABLE Student(
	Name NVARCHAR(50),
	Birthday DATE,
	StudentID NVARCHAR(10) NOT NULL PRIMARY KEY,
	EnrollDate DATE DEFAULT GETDATE(),
	GraduateDate Date,
)
GO

CREATE TABLE _Group(
	GroupID NVARCHAR(10) NOT NULL PRIMARY KEY,
	GroupSize int DEFAULT 1
)
GO

CREATE TABLE GroupStudents(
	GroupID NVARCHAR(10) 
		FOREIGN KEY REFERENCES _Group(GroupID) 
			ON DELETE CASCADE ON 
			UPDATE CASCADE,
	StudentID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Student(StudentID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,

	PRIMARY KEY (GroupID, StudentID)
)
GO

CREATE TABLE Assignment(
AssignmentID INT IDENTITY(1,1),
Attemps INT DEFAULT 0,
Grade INT,
GroupID NVARCHAR(10) 
	FOREIGN KEY REFERENCES _Group(GroupID) 
		ON DELETE SET NULL
		ON UPDATE CASCADE
		DEFAULT NULL,
CourseID NVARCHAR(10) 
	FOREIGN KEY REFERENCES Course(CourseID) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE,
PRIMARY KEY(AssignmentID),
CHECK(Grade<=12 AND Grade>=-3)

)
GO

CREATE TABLE Grader(
	TeacherID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Teacher(TeacherID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	AssignmentID INT 
		FOREIGN KEY REFERENCES Assignment(AssignmentID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,

	PRIMARY KEY(TeacherID, AssignmentID)
)
GO

CREATE TABLE Enrolled(
	Status NVARCHAR(50),
	CourseID NVARCHAR(10) 
		FOREIGN KEY (CourseID) REFERENCES Course(CourseID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	StudentID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Student(StudentID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,

	PRIMARY KEY(CourseID, StudentID)
)
GO


CREATE TABLE Calendar(
	CourseID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Course(CourseID) 
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	Type NVARCHAR(50) DEFAULT 'Deadline',
	_DateTime DATETIME DEFAULT '2000-01-01 00:00:00',

	PRIMARY KEY(CourseID, Type, _DateTime)
)
GO



CREATE TABLE ContentArea(
	TextBlock NVARCHAR(50) DEFAULT NULL,
	GroupSignupLink NVARCHAR(50) DEFAULT NULL,
	Audio NVARCHAR(50) DEFAULT NULL,
	Video NVARCHAR(50) DEFAULT NULL,
	AreaID NVARCHAR(10) PRIMARY KEY
)
GO

CREATE TABLE Folder(
	FolderID NVARCHAR(10),
	PRIMARY KEY(FolderID)
)
GO


CREATE TABLE AreaToFolder(
	AreaID NVARCHAR(10) 
		FOREIGN KEY REFERENCES ContentArea(AreaID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	FolderID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Folder(FolderID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	PRIMARY KEY(FolderID, AreaID)
)
GO


CREATE TABLE CourseContent(
	CourseID NVARCHAR(10) 
		FOREIGN KEY REFERENCES Course(CourseID)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	ContentID NVARCHAR(10),
		
	PRIMARY KEY(ContentID)

)
GO


CREATE TABLE ContentToArea(
	CourseContent NVARCHAR(10) 
		FOREIGN KEY REFERENCES CourseContent(ContentID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	ContentArea NVARCHAR(10)
		FOREIGN KEY REFERENCES ContentArea(AreaID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE
)
GO


CREATE TABLE ContentToFolder(
	CourseContent NVARCHAR(10) 
		FOREIGN KEY REFERENCES CourseContent(ContentID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	ContentFolder NVARCHAR(10)
		FOREIGN KEY REFERENCES Folder(FolderID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE
)
GO
	



